### PR TITLE
Feat/xxx/json ld

### PR DESCRIPTION
**Pull request by morrieinmaas**

### CODE REVIEW

**Comment by morrieinmaas** [comment]
needs json log #164 to be merged first

**Comment by morrieinmaas** [comment]
Sure. I already assumed this. Just did this for fun over the weekend

**Comment by morrieinmaas** [comment]
@blu3beri maybe we can define how this redesign should look like before the holidays?

**Comment by blu3beri** [comment]
> @blu3beri maybe we can define how this redesign should look like before the holidays?

I will do my best.

**Comment by morrieinmaas** [comment]
> > @blu3beri maybe we can define how this redesign should look like before the holidays?
> 
> I will do my best.

no worries if it turns out to be later

**Comment by blu3beri** [comment]
@morrieinmaas I will close this for now. There are quite a bit of merge conflicts and we might need to do some rethinking of the API for the cli.

**Pull request closed without merging**
